[platformio]
default_envs = esp32dev

[env:native]
platform = native
build_flags =
    -std=c++17
    -Iinclude
    -I.
lib_ldf_mode = off

test_build_src = yes

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
build_flags =
    -DCORE_DEBUG_LEVEL=3
    -I.
lib_deps =
    me-no-dev/ESPAsyncWebServer
    me-no-dev/AsyncTCP
    bblanchon/ArduinoJson
